"""Broker execution interface. Paper and live are the SAME class pointed at
different Alpaca base URLs — that is the whole point of choosing Alpaca.
The backtester implements this Protocol too, so OrderManager is reused there.
"""
from __future__ import annotations

from typing import Protocol

from core.models import Order, OrderIntent, Position


class ExecutionClient(Protocol):
    def submit(self, intent: OrderIntent) -> Order: ...
    def cancel(self, client_order_id: str) -> None: ...
    def get_order_by_client_id(self, client_order_id: str) -> Order | None: ...
    def open_orders(self) -> list[Order]: ...
    def positions(self) -> list[Position]: ...
    def account_equity(self) -> tuple:  # (equity, settled_cash, buying_power)
        ...
    def close_all_positions(self) -> list[Order]:
        """Kill switch primitive: cancel all open orders, market-flatten all."""
        ...
